/**
 * System Lifecycle Status Constants
 */
const STATUSES = {
  EMPLOYEE: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    ON_LEAVE: 'ON_LEAVE',
    TERMINATED: 'TERMINATED'
  },
  CONTRACT: {
    DRAFT: 'DRAFT',
    ACTIVE: 'ACTIVE',
    EXPIRED: 'EXPIRED',
    TERMINATED: 'TERMINATED'
  },
  ATTENDANCE: {
    PRESENT: 'PRESENT',
    LATE: 'LATE',
    HALF_DAY: 'HALF_DAY',
    ABSENT: 'ABSENT',
    ON_LEAVE: 'ON_LEAVE'
  },
  TIMEOFF_REQUEST: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REFUSED: 'REFUSED',
    CANCELLED: 'CANCELLED'
  },
  TIMEOFF_ALLOCATION: {
    DRAFT: 'DRAFT',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED'
  },
  PAYRUN: {
    DRAFT: 'DRAFT',
    COMPUTED: 'COMPUTED',
    VALIDATED: 'VALIDATED',
    PAID: 'PAID'
  },
  PAYSLIP: {
    UNPAID: 'UNPAID',
    PAID: 'PAID'
  },
  FACE_ENROLLMENT: {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    ACTIVE: 'ACTIVE',
    FAILED: 'FAILED',
    REVOKED: 'REVOKED'
  },
  FACE_LOG: {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    REJECTED: 'REJECTED'
  },
  SALARY_RULE_CATEGORY: {
    BASIC: 'BASIC',
    ALLOWANCE: 'ALLOWANCE',
    GROSS: 'GROSS',
    DEDUCTION: 'DEDUCTION',
    NET: 'NET'
  },
  SALARY_COMPUTATION_TYPE: {
    FIXED: 'FIXED',
    PERCENTAGE: 'PERCENTAGE',
    FORMULA: 'FORMULA'
  }
};

module.exports = STATUSES;
